root = "."
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "./bin/server"
  cmd = "go build -buildvcs=false -o ./bin/server ./examples/basic/"
  delay = 1000
  exclude_dir = ["frontend", "assets", "tmp", "bin", "vendor", "testdata", "docs"]
  exclude_file = []
  exclude_regex = ["_test.go", "_mock", ".*_templ.go", ".*_enum.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "templ", "html", "env"]
  include_file = [".env"]
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  pre_cmd = ["go generate ./...", "make build/tailwind"]
  post_cmd = []
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true

# [proxy]
#   enabled = true
#   proxy_port = 8080
#   app_port = 3000
